lexik_jwt_authentication:
  private_key_path: '%kernel.project_dir%/config/jwt/private.pem'
  public_key_path: '%kernel.project_dir%/config/jwt/public.pem'
  pass_phrase: '%env(JWT_PASSPHRASE)%'  # This should match the passphrase used when generating the private key
  token_ttl: 36000  # Token time-to-live in seconds
