version: '3.3'

networks:
    default:
        external:
            name: backend_task_backend
    backend_task_backend:
        driver: bridge
    backend_task_frontend:
        driver: bridge

services:
    mailhog:
        image: mailhog/mailhog:v1.0.1
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - backend_task_backend

    db:
        platform: linux/amd64
        image: mysql:8.0
        ports:
            - "3307:3306"
        volumes:
            - backend_task_database_data_new:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: docker
            MYSQL_DATABASE: debricked
            MYSQL_USER: aman
            MYSQL_PASSWORD: aman
        restart: on-failure
        networks:
            - backend_task_backend

    rabbitmq:
        image: rabbitmq:3.9-management-alpine
        environment:
            RABBITMQ_ERLANG_COOKIE: rabbitmqcookie
            RABBITMQ_DEFAULT_USER: rabbit
            RABBITMQ_DEFAULT_PASS: docker
        volumes:
            - backend_task_rabbitmqetc:/etc/rabbitmq/
            - backend_task_rabbitmqdata:/var/lib/rabbitmq/
            - backend_task_rabbitmqlogs:/var/log/rabbitmq/
        networks:
            - backend_task_backend
        restart: on-failure
        ports:
            - "5672:5672"
            - "15672:15672"

    php:
        image: ghcr.io/debricked/docker-image-php-xdebug:latest
        environment:
            # Reference https://gist.github.com/jehaby/61a89b15571b4bceee2417106e80240d
            PHP_IDE_CONFIG: "serverName=docker.php.cli"
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_SOCKET: tcp://webserver:8707
            REDIS_HOST: redis
            REDIS_PORT: 6379
            IN_DOCKER: "true"
            DB_HOST: db
            DB_USER: aman
            DB_PASSWORD: aman
            DB_NAME: debricked
        expose:
            - 9000
            - 9001
        ports:
            - "8000:8000"
        volumes:
            - ./:/var/www/html
            - ./wait-for-it.sh:/wait-for-it.sh
        depends_on:
            - db
            - rabbitmq
            - mailhog
        entrypoint:
            - /bin/sh
            - -c
            - ip -4 route list match 0/0 | awk '{print $$3" host.docker.internal"}' >> /etc/hosts && php-fpm --allow-to-run-as-root
        restart: on-failure
        tty: true
        user: root
        shm_size: 2g
        networks:
            - backend_task_backend
        build:
            context: .
            dockerfile: Dockerfile
        command: ["./wait-for-it.sh", "db:3306", "--", "sh", "-c", "RUN sh ./doctrine-etrypoint.sh"]

    nginx:
        image: nginx:latest
        environment:
            # Exposes the host Blackfire IDs and tokens environment variables.
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_SOCKET: tcp://webserver:8707
        ports:
            - "8888:80"
            - "8707:8707"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/html
        depends_on:
            - php
        restart: on-failure
        user: root
        networks:
            - backend_task_backend
            - backend_task_frontend

volumes:
    backend_task_database_data:
        driver: local
    backend_task_database_data_new:
        driver: local
    backend_task_rabbitmqetc:
        driver: local
    backend_task_rabbitmqdata:
        driver: local
    backend_task_rabbitmqlogs:
        driver: local